export const GET_NEWS = 'GET_NEWS';
export const GET_ALL_NEWS_SUCCESS = 'GET_ALL_NEWS_SUCCESS';
export const GET_NEWS_BY_USER_SUCCESS = 'GET_NEWS_BY_USER_SUCCESS';
export const FILTER_NEWS = 'FILTER_NEWS';
export const CLEAR_NEWS = 'CLEAR_NEWS';
